### ISSUE TITLE
scrapy-do is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by jpdmostwanted** [ljanyst/scrapy-do#17]
I installed the package using `pip install scrapy-do`
When I try to run the next command ` scrapy-do -n scrapy-do` I get the the error
*scrapy-do is not recognized as an internal or external command,
operable program or batch file.*

**Comment by ljanyst** [comment]
Which version of `twisted` are you using?

`]==> pip show twisted`

**Comment by jpdmostwanted** [comment]
Name: Twisted
Version: 19.2.0
Summary: An asynchronous networking framework written in Python
Home-page: http://twistedmatrix.com/
Author: Twisted Matrix Laboratories
Author-email: twisted-python@twistedmatrix.com
License: MIT
Location: c:\users\jyotirmaya.prusty\appdata\local\programs\python\python37-32\lib\site-packages
Requires: constantly, hyperlink, attrs, incremental, Automat, zope.interface, PyHamcrest
Required-by: scrapyd, Scrapy

**Comment by ljanyst** [comment]
Scrapy Do is meant to run on a server, which mostly means Linux. While there is probably no reason why it can't run on Windows, I have never tested it. If you feel like making it work on Windows, you're very welcome to submit a pull request.

For the time being, I will close the ticket.

**Comment by bobs-bg** [comment]
@Ijanyst very useful answer, 
Thanks...
