### ISSUE TITLE
"Maximum call stack size exceeded" error reported by Chrome when viewing large file on Completed Jobs page

### ISSUE THREAD

**Issue by linan-github** [ljanyst/scrapy-do#25]
This issue is observed v0.4.0

Nothing is shown when trying to view a large log file from **Completed Jobs** page. And Chrome insepct shows error "Maximum call stack size exceeded" on [link](https://github.com/ljanyst/scrapy-do/blob/3929bb66d910803e7ec9cee77dcbe1df39c9a572/ui/src/components/LogViewer.js#L56).

Stackorverflow has suggestions on how to handle this error:
https://stackoverflow.com/questions/49123222/converting-array-buffer-to-string-maximum-call-stack-size-exceeded

Hope this issue can be fixed soon. For now I have reverted to use v0.3.2.

**Comment by ljanyst** [comment]
This code has been completely rewritten. Can you please have a look at master and see if your issue is fixed?
