### ISSUE TITLE
project deployment relying on external dependencies

### ISSUE THREAD

**Issue by mxdev88** [ljanyst/scrapy-do#28]
The [documentation](https://scrapy-do.readthedocs.io/en/latest/basic-concepts.html#projects) explains how to zip and [push](https://scrapy-do.readthedocs.io/en/latest/commandline-client.html#push-project)  a project.

How do you package and upload a project that relies on external dependencies?
e.g:
- project_A uses lib X
- project_B uses lib Y and Z

assuming lib X, Y and Z are not part of Scrapy.

When running push-project that uses external dependencies, the upload fails.
```
scrapy-do-cl --url http://ip:7654 push-project --project-path /path/to/my-project
````
the above command returns
```
[!] Server responded with an error: Unable to get the list of spiders
```
It does not give much details as to why it could not list the spiders. It took a bit of debugging to understand it was coming from missing libs since `scrapy list` worked locally.

**Comment by ljanyst** [comment]
Indeed, the error message needs to be improved. Thanks for pointing this out.
