### ISSUE TITLE
Access to OS Environment Variables to Spiders

### ISSUE THREAD

**Issue by sushilsingh95** [ljanyst/scrapy-do#30]
Hi @ljanyst ,

First of all thanks for creating this awesome daemon It has some awesome scheduling capabilities which official scrapyd is misisng.

Recently I started using scrapy-do and found out that spiders running in scrapy-do daemon don't have access to os environment variables.

My Usecase is like this: I have a scrapy project which has an scrapy extension that manages the db connection. Now db credentials to that extension are provided by scrapy settings module. Scrapy settings module gets those credentials from environment variables.

This setup works fine when I directly run scrapy using `scrapy crawl ...` command. But face issues while running with scrapy-do daemon.

I saw this issue: https://github.com/ljanyst/scrapy-do/issues/19 and corresponding PR: https://github.com/ljanyst/scrapy-do/pull/20. I don't agree with the statement that "The server environment really should not spill to the spiders". There are valid use cases to support that. Mine is an example. Infact, scrapyd also has support for passing OS environment variables to spiders. See:
https://github.com/scrapy/scrapyd/blob/master/scrapyd/environ.py#L12
https://github.com/scrapy/scrapyd/blob/master/scrapyd/environ.py#L25
https://github.com/scrapy/scrapyd/blob/master/scrapyd/launcher.py#L41

So can we have this feature anytime soon? Optionally, we can have some feature flags to prevent accidental exposure of os env variables to spiders.

**Comment by ljanyst** [comment]
Thanks for the compliment @sushilsingh95 

Is there a reason you need to get the credentials from the environment? I can think of some, but they are pretty far fetched.

Scrapyd is not exactly a marvel of engineering, so I don't accept the fact that they do something as an argument that carries any weight whatsoever.

**Comment by ljanyst** [comment]
Closing for now. Please feel free to re-open if you feel this issue needs further discussion.

**Comment by dot-mike** [comment]
@ljanyst  thanks for providing this awesome project!

Accessing environment variables is highly needed (I would say critical) to ensure code does not contain private stuff.
A use case is to deploy this project through Docker and use Docker-compose to provide variables for Scrapy  through **settings.py**:
```python
import os
[....]
MONGO_URI = os.environ.get("MONGO_URI", "mongodb://localhost:27017")
MONGO_DATABASE = os.environ.get("MONGO_DATABASE", "database")
MONGO_COLLECTION = os.environ.get("MONGO_COLLECTION", "collection")
MONGO_USER = os.environ.get("MONGO_USER", "")
MONGO_PW = os.environ.get("MONGO_PW", "")
```
