### ISSUE TITLE
Error after creating a job

### ISSUE THREAD

**Issue by ghost** [ljanyst/scrapy-do#31]
Hi, thanks for creating scrapy-do.

I tried to create a job for running a spider but scrapy-do found an error in /scrapy_do/webservice.py in the line 256. 
I suppose this is why my jobs don't work and are exited with code 1, seconds after created.

Also, I cant get logs neither in command line nor Web interface but I dont know if there is something I need to configure.

Thank you for this framework-API.

**Comment by ljanyst** [comment]
What error exactly?

**Comment by ghost** [comment]
filename = os.path.basename(urllib.parse.unquote(request.path))
          File "/usr/lib/python3.8/urllib/parse.py", line 634, in unquote
            if '%' not in string:
        builtins.TypeError: a bytes-like object is required, not 'str'

**Comment by ljanyst** [comment]
Which version of Twisted are you using? You may need to upgrade.
